# Generated by Django 5.2.6 on 2025-10-14 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomy', '0003_researchproject_researchtemplate_and_more'),
        ('core', '0004_blogpost_content_type_blogimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type_research',
            field=models.CharField(choices=[('projects', 'Projects'), ('research', 'Research')], default='projects', max_length=20),
        ),
        migrations.CreateModel(
            name='AllResearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(choices=[('Astronomy', 'Astronomy'), ('AI & Machine Learning', 'AI & Machine Learning'), ('Physics', 'Physics'), ('Engineering', 'Engineering'), ('Mathematics', 'Mathematics'), ('Other', 'Other')], max_length=100)),
                ('astro_research', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='astronomy.researchproject')),
            ],
        ),
    ]
