# Generated by Django 5.2.6 on 2025-10-14 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_project_type_research_allresearch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type_research',
            new_name='type_project',
        ),
        migrations.AddField(
            model_name='project',
            name='research_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.allresearch'),
        ),
    ]
