# Generated by Django 5.2.6 on 2025-10-18 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_type_research_project_type_project_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentsProjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_doc', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('projects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.project')),
            ],
        ),
    ]
