# Generated by Django 5.2.6 on 2025-10-18 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_documentsprojects'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentsprojects',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
