# Generated by Django 5.2.6 on 2025-10-19 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_documentsprojects_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image_icon',
            field=models.ImageField(blank=True, null=True, upload_to='skills/'),
        ),
    ]
