# Generated by Django 5.2.6 on 2025-10-20 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_contactlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactLog',
        ),
    ]
