# Generated by Django 5.2.6 on 2025-09-09 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CelestialObjects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('object_type', models.CharField(choices=[('planet', 'Planet'), ('star', 'Star'), ('galaxy', 'Galaxy'), ('nebula', 'Nebula'), ('cluster', 'Star Cluster'), ('moon', 'Moon'), ('comet', 'Comet'), ('asteroid', 'Asteroid'), ('other', 'Other')], max_length=20)),
                ('constellation', models.CharField(blank=True, max_length=100)),
                ('distance_ly', models.CharField(blank=True, help_text='Distance in light years', max_length=100)),
                ('magnitude', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObservationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('observation_date', models.DateTimeField()),
                ('object_name', models.CharField(max_length=100)),
                ('location', models.CharField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('seeing', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Terrible')])),
                ('transparency', models.IntegerField(choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Terrible')])),
                ('moon_phase', models.CharField(blank=True, max_length=50)),
                ('temperature', models.IntegerField(blank=True, help_text='Temperature in Celsius', null=True)),
                ('telescope', models.CharField(blank=True, max_length=100)),
                ('eyepiece', models.CharField(blank=True, max_length=100)),
                ('magnification', models.CharField(blank=True, max_length=50)),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField()),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celestial_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='astronomy.celestialobjects')),
            ],
            options={
                'ordering': ['-observation_date'],
            },
        ),
        migrations.CreateModel(
            name='AstroPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('image', models.ImageField(upload_to='astronomy/photos/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='astronomy/thumbnails/')),
                ('object_name', models.CharField(max_length=100)),
                ('capture_date', models.DateTimeField()),
                ('exposure_time', models.CharField(blank=True, max_length=50)),
                ('iso', models.IntegerField(blank=True, null=True)),
                ('aperture', models.CharField(blank=True, max_length=20)),
                ('focal_length', models.CharField(blank=True, max_length=20)),
                ('frames', models.IntegerField(blank=True, help_text='Number of frames stacked', null=True)),
                ('telescope', models.CharField(blank=True, max_length=100)),
                ('camera', models.CharField(blank=True, max_length=100)),
                ('mount', models.CharField(blank=True, max_length=100)),
                ('processing_software', models.CharField(blank=True, max_length=100)),
                ('processing_notes', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('celestial_objects', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='astronomy.celestialobjects')),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='astronomy.observationlog')),
            ],
            options={
                'ordering': ['-capture_date'],
            },
        ),
    ]
