# Generated by Django 5.2.6 on 2025-10-08 05:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomy', '0002_alter_astrophoto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('research_type', models.CharField(choices=[('orbital', 'Orbital Period Measurement'), ('variable_star', 'Variabe Star Observation'), ('meteor', 'Meteor Shower Study'), ('eclipse', 'Eclipse Documentation'), ('planetary', 'Planetary Observation'), ('deep_sky', 'Deep Sky Observation'), ('occultation', 'Occultation Timing'), ('sunspot', 'Sunspot Monitoring'), ('custom', 'Custom Research')], max_length=20)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('target_duration_days', models.IntegerField(help_text='Planned duration in days')),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('hypothesis', models.TextField(blank=True, help_text='What you want to prove/measure')),
                ('expected_results', models.TextField(blank=True)),
                ('actual_results', models.TextField(blank=True)),
                ('conclusions', models.TextField(blank=True)),
                ('data_template', models.JSONField(blank=True, default=dict, help_text='Template for data collection fields')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResearchTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('research_type', models.CharField(choices=[('orbital', 'Orbital Period Measurement'), ('variable_star', 'Variabe Star Observation'), ('meteor', 'Meteor Shower Study'), ('eclipse', 'Eclipse Documentation'), ('planetary', 'Planetary Observation'), ('deep_sky', 'Deep Sky Observation'), ('occultation', 'Occultation Timing'), ('sunspot', 'Sunspot Monitoring'), ('custom', 'Custom Research')], max_length=20)),
                ('description', models.TextField()),
                ('template_config', models.JSONField()),
                ('instruction', models.TextField(help_text='Step-by-step guide for this research')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='astrophoto',
            options={'ordering': ['-capture_date', 'sequence_number']},
        ),
        migrations.AlterModelOptions(
            name='celestialobjects',
            options={'verbose_name_plural': 'Celestial Objects'},
        ),
        migrations.AddField(
            model_name='astrophoto',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='astrophoto',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='astrophoto',
            name='sequence_number',
            field=models.IntegerField(blank=True, help_text='For time-series observations', null=True),
        ),
        migrations.AddField(
            model_name='astrophoto',
            name='stacked_frames',
            field=models.IntegerField(blank=True, help_text='Number of frames stacked', null=True),
        ),
        migrations.AddField(
            model_name='celestialobjects',
            name='orbital_period',
            field=models.FloatField(blank=True, help_text='Days', null=True),
        ),
        migrations.AddField(
            model_name='celestialobjects',
            name='parent_object',
            field=models.ForeignKey(blank=True, help_text='For satellites, parent planet', null=True, on_delete=django.db.models.deletion.SET_NULL, to='astronomy.celestialobjects'),
        ),
        migrations.AddField(
            model_name='celestialobjects',
            name='semi_major_axis',
            field=models.FloatField(blank=True, help_text='km', null=True),
        ),
        migrations.AddField(
            model_name='eclipseobservation',
            name='danjon_scale',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('L0', 'L0 - Very dark'), ('L1', 'L1 - Dark gray/brown'), ('L2', 'L2 - Deep red/rust'), ('L3', 'L3 - Brick red'), ('L4', 'L4 - Bright copper/orange')], help_text='Brightness scale for total lunar eclipses (L0-L4)', max_length=2),
        ),
        migrations.AddField(
            model_name='observationlog',
            name='cloud_cover',
            field=models.IntegerField(default=0, help_text='Percentage of 0-100', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='observationlog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='astrophoto',
            name='aperture',
            field=models.CharField(blank=True, help_text='e.g., f/8', max_length=20),
        ),
        migrations.AlterField(
            model_name='astrophoto',
            name='exposure_time',
            field=models.CharField(blank=True, help_text='e.g., 1/125s or 30s', max_length=50),
        ),
        migrations.AlterField(
            model_name='astrophoto',
            name='focal_length',
            field=models.CharField(blank=True, help_text='mm', max_length=20),
        ),
        migrations.AlterField(
            model_name='astrophoto',
            name='image',
            field=models.ImageField(upload_to='astronomy/photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='celestialobjects',
            name='object_type',
            field=models.CharField(choices=[('planet', 'Planet'), ('star', 'Star'), ('galaxy', 'Galaxy'), ('nebula', 'Nebula'), ('cluster', 'Star Cluster'), ('moon', 'Moon'), ('satellite', 'Planetary Satellite'), ('comet', 'Comet'), ('asteroid', 'Asteroid'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='observationlog',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='observationlog',
            name='temperature',
            field=models.IntegerField(blank=True, help_text='Celsius', null=True),
        ),
        migrations.CreateModel(
            name='ResearchDataEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation_datetime', models.DateTimeField()),
                ('days_from_start', models.FloatField(editable=False, help_text='Auto-calculated from project start')),
                ('data', models.JSONField(help_text='Flexible data storage')),
                ('data_quality', models.IntegerField(blank=True, choices=[(5, 'Excellent'), (4, 'Good'), (3, 'Average'), (2, 'Poor'), (1, 'Terrible')], null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_outlier', models.BooleanField(default=False, help_text='Mark as statistical outlier')),
                ('is_validated', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_data', to='astronomy.observationlog')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_entries', to='astronomy.researchproject')),
            ],
            options={
                'verbose_name_plural': 'Research Data Entries',
                'ordering': ['observation_datetime'],
            },
        ),
        migrations.CreateModel(
            name='ResearchAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analysis_type', models.CharField(choices=[('period', 'Orbital Period Calculation'), ('kepler', "Kepler's Law Verification"), ('light_curve', 'Light Curve Analysis'), ('statistics', 'Statistical Analysis'), ('custom', 'Custom Analysis')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('results', models.JSONField()),
                ('theoretical_values', models.JSONField(blank=True, null=True)),
                ('error_percentage', models.JSONField(blank=True, null=True)),
                ('quality_rating', models.CharField(blank=True, choices=[('excellent', 'Excellent (<2% error)'), ('good', 'Good (2-5% error)'), ('fair', 'Fair (5-10% error)'), ('poor', 'Poor (>10% error)')], max_length=20, null=True)),
                ('methodology', models.TextField(help_text='How the analysis was performed')),
                ('interpretation', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='astronomy.researchproject')),
            ],
            options={
                'verbose_name_plural': 'Research Analysis',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='astrophoto',
            name='research_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='photos', to='astronomy.researchproject'),
        ),
        migrations.AddField(
            model_name='observationlog',
            name='research_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='observation', to='astronomy.researchproject'),
        ),
    ]
