# Generated by Django 5.2.6 on 2025-10-24 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astronomy', '0003_researchproject_researchtemplate_and_more'),
        ('research', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchproject',
            name='linked_astro_project',
            field=models.ForeignKey(blank=True, help_text='Link to astronomy app research project (for astronomy field only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='general_research_projects', to='astronomy.researchproject'),
        ),
        migrations.AlterField(
            model_name='researchproject',
            name='field',
            field=models.CharField(choices=[('ai', 'AI & Machine Learning'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('engineering', 'Engineering'), ('astronomy', 'Astronomy'), ('other', 'Other')], max_length=20),
        ),
    ]
