# Generated by Django 5.2.6 on 2025-10-24 22:00

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('research', '0005_remove_experiment_project_remove_note_project_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Judul penelitian', max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('field', models.CharField(choices=[('ai', 'AI & Machine Learning'), ('physics', 'Physics'), ('mathematics', 'Mathematics'), ('engineering', 'Engineering'), ('astronomy', 'Astronomy'), ('other', 'Other')], help_text='Bidang penelitian', max_length=20)),
                ('description', models.TextField(help_text='Deskripsi singkat penelitian')),
                ('objectives', models.TextField(help_text='Tujuan penelitian')),
                ('methodology', models.TextField(blank=True, help_text='Metode yang digunakan')),
                ('hypothesis', models.TextField(blank=True, help_text='Hipotesis (jika ada)')),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('archived', 'Archived')], default='planning', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('progress_percentage', models.IntegerField(default=0, help_text='Progress dalam persentase (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('findings', models.TextField(blank=True, help_text='Temuan/hasil penelitian')),
                ('conclusions', models.TextField(blank=True, help_text='Kesimpulan')),
                ('future_work', models.TextField(blank=True, help_text='Rencana pengembangan selanjutnya')),
                ('data_schema', models.JSONField(blank=True, default=dict, help_text='Data fleksibel dalam format JSON untuk kebutuhan spesifik per bidang')),
                ('institution', models.CharField(blank=True, help_text='Institusi/organisasi', max_length=200)),
                ('supervisor', models.CharField(blank=True, help_text='Supervisor/pembimbing', max_length=200)),
                ('collaborators', models.TextField(blank=True, help_text='Kolaborator/tim (satu per baris)')),
                ('is_public', models.BooleanField(default=False, help_text='Apakah riset ini public?')),
                ('is_published', models.BooleanField(default=False, help_text='Sudah dipublikasikan?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Research Project',
                'verbose_name_plural': 'Research Projects',
                'ordering': ['-updated_at', '-created_at'],
                'indexes': [models.Index(fields=['field', 'status'], name='research_re_field_e45103_idx'), models.Index(fields=['user', '-created_at'], name='research_re_user_id_f924e6_idx')],
            },
        ),
    ]
