# Generated by Django 5.2.6 on 2025-11-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pomodorosettings',
            name='notification_sound',
            field=models.CharField(choices=[('bell', '🔔 Bell'), ('chime', '🎵 Chime'), ('birds', '🐦 Birds'), ('none', '🔇 None')], default='bell', max_length=20),
        ),
    ]
